### ISSUE TITLE
Inconsistent units in expression

### ISSUE THREAD

**Issue by rlcamp** [patnr/FM#1]
There appears to be a unit issue in the algorithm. The expression "time = min(xmin1, ymin1) + 1/Fij" implies that 1/Fij has the same units as the other quantities, which it does not. A possible correction is time = xmin1 + dx / Fij or time = ymin1 + dy / Fij, depending on whether xmin1 or ymin1 is smaller.

https://github.com/patnr/FM/blob/029218ce0dea51313c560132097fb15732ae0293/functions/fm2d.m#L312

**Comment by patnr** [comment]
That seems right, yes. And the error is also present in the other implementations
- https://github.com/patnr/FM/blob/029218ce0dea51313c560132097fb15732ae0293/functions/fm3d.m#L249
- https://github.com/patnr/FM/blob/029218ce0dea51313c560132097fb15732ae0293/functions/fm2dc.cpp#L352
- https://github.com/patnr/FM/blob/029218ce0dea51313c560132097fb15732ae0293/functions/fm3dc.cpp#L409

The test scripts (`TS_`) haven't helped me detect it before because `order` 1 is only used in
-  `TS_maze` where `dx==dy`
- `TS_fm2dc` where only `order` 1 implementations get compared
- `TS_bar` which is physically 1d.

Thanks for pointing it out. Want to make a PR?
